"""add_admin_and_lead_status_fields

Revision ID: 1f6b4422db7a
Revises: ce1e90fdcfc9
Create Date: 2026-04-26 02:45:19.121200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f6b4422db7a'
down_revision: Union[str, None] = 'ce1e90fdcfc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('public_leads', sa.Column('status', sa.String(), server_default='completed', nullable=False))
    op.add_column('public_leads', sa.Column('is_approved', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('public_leads', sa.Column('error_message', sa.Text(), nullable=True))
    op.alter_column('public_leads', 'report_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.alter_column('public_leads', 'report_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('public_leads', 'error_message')
    op.drop_column('public_leads', 'is_approved')
    op.drop_column('public_leads', 'status')
    # ### end Alembic commands ###
