"""Add public leads and credits

Revision ID: ce1e90fdcfc9
Revises: ee6c748cb1ae
Create Date: 2026-04-25 14:39:24.312383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce1e90fdcfc9'
down_revision: Union[str, None] = 'ee6c748cb1ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_leads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('opportunity_score', sa.String(), nullable=False),
    sa.Column('teaser_insight', sa.Text(), nullable=False),
    sa.Column('teaser_revenue_leak', sa.String(), nullable=True),
    sa.Column('report_json', sa.JSON(), nullable=False),
    sa.Column('website_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_public_leads_category', 'public_leads', ['category'], unique=False)
    op.create_index('idx_public_leads_freshness', 'public_leads', ['updated_at'], unique=False)
    op.create_index('idx_public_leads_location', 'public_leads', ['location'], unique=False)
    op.create_index('idx_public_leads_score', 'public_leads', ['opportunity_score'], unique=False)
    op.create_table('lead_unlocks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['public_leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'lead_id', name='uix_user_lead_unlock')
    )
    op.add_column('users', sa.Column('credits', sa.Integer(), nullable=False, server_default='5'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'credits')
    op.drop_table('lead_unlocks')
    op.drop_index('idx_public_leads_score', table_name='public_leads')
    op.drop_index('idx_public_leads_location', table_name='public_leads')
    op.drop_index('idx_public_leads_freshness', table_name='public_leads')
    op.drop_index('idx_public_leads_category', table_name='public_leads')
    op.drop_table('public_leads')
    # ### end Alembic commands ###
