"""add_monthly_tracking_fields

Revision ID: ee6c748cb1ae
Revises: fbccc92d70fe
Create Date: 2026-04-23 01:03:22.786342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee6c748cb1ae'
down_revision: Union[str, None] = 'fbccc92d70fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reports_this_month', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('last_month_reset', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_month_reset')
    op.drop_column('users', 'reports_this_month')
    # ### end Alembic commands ###
