"""add_subscription_and_quota_fields

Revision ID: fbccc92d70fe
Revises: 773376a3a2c3
Create Date: 2026-04-23 00:32:01.696832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbccc92d70fe'
down_revision: Union[str, None] = '773376a3a2c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reports_purchased', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('reports_today', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('last_report_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_report_date')
    op.drop_column('users', 'reports_today')
    op.drop_column('users', 'reports_purchased')
    op.drop_column('users', 'subscription_id')
    # ### end Alembic commands ###
